//
// pch.cpp
//

#include "pch.h"
#include "TupleTest.h"
#include "TupleDescTest.h"
#include "CatalogTest.h"
#include "HeapPageIdTest.h"
#include "RecordIdTest.h"
#include "HeapPageReadTest.h"
#include "HeapFileReadTest.h"
#include "ScanTest.h"
#include "PredicateTest.h"
#include "JoinPredicateTest.h"
#include "FilterTest.h"
#include "JoinTest.h"
#include "SysFilterTest.h"
#include "SysJoinTest.h"
#include "IntegerAggregatorTest.h"
#include "StringAggregatorTest.h"
#include "AggregateTest.h"
#include "SysAggregateTest.h"
#include "HeapPageWriteTest.h"
#include "HeapFileWriteTest.h"